### ISSUE TITLE
Could not run the code

### ISSUE THREAD

**Issue by Leo-8991** [mtamburrano/LBD_Descriptor#1]
Hello @mtamburrano,
I tried to run this code but got this error; 

[ 33%] Building CXX object CMakeFiles/LineMatchingLib.dir/LineDescriptor.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: **\* [CMakeFiles/LineMatchingLib.dir/LineDescriptor.cpp.o] Error 1
make[1]: **\* [CMakeFiles/LineMatchingLib.dir/all] Error 2
make: **\* [all] Error 2

My environment is: Ubuntu 12.04LTS 64bit, OprnCV 2.4.10.
It would help me a lot if you help with the information about the envionment that you used.
Hoping to hear from you soon.
Thank you for your time.

**Comment by bhack** [comment]
@Leo-8991 LBD descriptor is now at https://github.com/Itseez/opencv_contrib. Try to use that and open further ticket there.
