### ISSUE TITLE
remove BIAS dependecies in PairwiseMatching

### ISSUE THREAD

**Issue by lligen** [mtamburrano/LBD_Descriptor#2]
hello, 
         I am interested if you have removed BIAS dependecies in PairwiseMatching part, if not, i think i will do this part with EIGEN library.
         ~~

**Comment by mtamburrano** [comment]
hi,
If I remember it correctly, I removed BIAS only in the parts needed to compute the descriptors, probably in the matching part BIAS dependencies are still there.
By the way with the Google Summer of Code of the last year,  I helped to include the LBD descriptors and a miHasher matcher into opencv_contrib, if you are familiar with opencv I think you'll find it easier to use than forking this repo.
The module is here: https://github.com/Itseez/opencv_contrib/tree/master/modules/line_descriptor
Hope this helps

**Comment by lligen** [comment]
OK, thx a lot .I will watch the module you provided.  
bests ~~
