### ISSUE TITLE
Build failed due to Undefined reference to cv::imread, cv::imwrite

### ISSUE THREAD

**Issue by chaiein** [mtamburrano/LBD_Descriptor#4]
[ 80%] Linking CXX executable TestLineMatchingAlgorithm
CMakeFiles/TestLineMatchingAlgorithm.dir/TestLineMatchingAlgorithm.cpp.o: In function `main':
TestLineMatchingAlgorithm.cpp:(.text.startup+0x101): undefined reference to `cv::imread(cv::String const&, int)'
TestLineMatchingAlgorithm.cpp:(.text.startup+0x211): undefined reference to `cv::imread(cv::String const&, int)'
TestLineMatchingAlgorithm.cpp:(.text.startup+0x877): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
TestLineMatchingAlgorithm.cpp:(.text.startup+0x910): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/TestLineMatchingAlgorithm.dir/build.make:98: recipe for target 'TestLineMatchingAlgorithm' failed
make[2]: *** [TestLineMatchingAlgorithm] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TestLineMatchingAlgorithm.dir/all' failed
make[1]: *** [CMakeFiles/TestLineMatchingAlgorithm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mtamburrano** [comment]
Probably it is due to OpenCV version, are you using 3.x?
Actually 2.4 is needed

**Comment by chaiein** [comment]
Yup i was using 3.1 version opencv. I solved this problem after installing opencv2.4.9 Thank you @mtamburrano :)
